"""Versioned core local-OS isolated-execution interface."""

from __future__ import annotations

from .contract import (
    AUDIT_ARCH_X86_64_V1,
    CLONE_NAMESPACE_FLAGS_MASK_V1,
    DENIED_CONTROL_OPERATIONS_V1,
    FCNTL_DENIED_COMMANDS_V1,
    FUTEX_PRIVATE_FLAG_V1,
    PIPE2_DENIED_FLAGS_V1,
    ISOLATION_PROFILE_V1,
    ISOLATION_REQUEST_SCHEMA_V1,
    LINUX_NATIVE_SUPERVISOR_V1,
    MAX_EXEC_ARGUMENT_ENVIRONMENT_BYTES_V1,
    MAX_LINUX_PATH_COMPONENTS_V1,
    MAX_PRIVATE_FILESYSTEM_BYTES_V1,
    MAX_PRIVATE_FILESYSTEM_INODES_V1,
    MAX_RAW_STREAM_BYTES_V1,
    MAX_RETAINED_STREAM_BYTES_V1,
    MAX_RUNTIME_HORIZON_NS_V1,
    NATIVE_SYSCALL_EXCLUSIVE_CEILING_X86_64_V1,
    READ_ONLY_ALLOWED_INODE_TYPES_V1,
    READ_ONLY_ROOT_SCAN_ENTRY_LIMIT_V1,
    READ_ONLY_TOTAL_SCAN_ENTRY_LIMIT_V1,
    REQUIRED_CAPABILITIES_V1,
    REQUIRED_CAPABILITY_SET_SHA256_V1,
    REQUIRED_OBSERVATION_CLASSES_V1,
    SOCKET_DENIAL_FILTER_SHA256_V1,
    SOCKET_DENIAL_FILTER_ROWS_V1,
    SOCKET_DENIAL_UNCONDITIONAL_SYSCALLS_V1,
    BackendProfileV1,
    ExecutableFormatV1,
    ExecutablePolicyV1,
    ExpectedFileIdentityV1,
    ExpectedFileTypeV1,
    FilesystemPolicyV1,
    IsolationRequestErrorCodeV1,
    IsolationRequestV1,
    IsolationRequestValidationV1,
    NetworkModeV1,
    NetworkPolicyV1,
    ObservationClassV1,
    OutputPolicyV1,
    ProcessPolicyV1,
    ReadOnlyRootV1,
    RequestIdentityV1,
    StreamPolicyV1,
    WorkloadIdentityV1,
    X32_SYSCALL_BIT_V1,
    effective_exec_argv_v1,
    effective_exec_environment_v1,
    validate_isolation_request_v1,
)
from .evidence import (
    ALLOWED_PROCESS_EVENT_CLASSES_V1,
    FILESYSTEM_QUOTA_FD_WRITE_SYSCALLS_X86_64_V1,
    FILESYSTEM_QUOTA_FD_TARGET_REGISTERS_X86_64_V1,
    ISOLATION_EVIDENCE_SCHEMA_V1,
    REQUIRED_FILESYSTEM_DENIAL_CLASSES_V1,
    REQUIRED_MEMFD_SEALS_V1,
    REQUIRED_NETWORK_DENIAL_CLASSES_V1,
    REQUIRED_OBSERVATION_EVENTS_V1,
    REQUIRED_STAGE_DEPENDENCIES_V1,
    STREAM_PIPE_CAPACITY_BYTES_V1,
    CleanupEvidenceV1,
    CorrelationEvidenceV1,
    EvidenceCompletenessV1,
    EvidenceStageStatusV1,
    EvidenceStageV1,
    EvidenceValidationErrorCodeV1,
    EvidenceValidationV1,
    ExecChainEvidenceV1,
    ExecutionEvidenceV1,
    ExecutionOutcomeV1,
    FilesystemEvidenceV1,
    FilesystemLimitKindV1,
    FilesystemLimitObservationV1,
    FilesystemLimitScopeV1,
    NetworkEvidenceV1,
    OSObservationV1,
    ObservedFileIdentityV1,
    ProcessEvidenceV1,
    ProcessMemberEvidenceV1,
    SecondaryExecDenialEvidenceV1,
    PrivateMountQuotaEvidenceV1,
    ReadOnlyRootScanEvidenceV1,
    StageDependencyV1,
    StreamCountV1,
    StreamDecodingStatusV1,
    StreamEvidenceV1,
    validate_execution_evidence_v1,
)


__all__ = [
    "ALLOWED_PROCESS_EVENT_CLASSES_V1",
    "AUDIT_ARCH_X86_64_V1",
    "BackendProfileV1",
    "CleanupEvidenceV1",
    "CLONE_NAMESPACE_FLAGS_MASK_V1",
    "CorrelationEvidenceV1",
    "DENIED_CONTROL_OPERATIONS_V1",
    "EvidenceCompletenessV1",
    "EvidenceStageStatusV1",
    "EvidenceStageV1",
    "EvidenceValidationErrorCodeV1",
    "EvidenceValidationV1",
    "ExecChainEvidenceV1",
    "ExecutableFormatV1",
    "ExecutablePolicyV1",
    "ExecutionEvidenceV1",
    "ExecutionOutcomeV1",
    "FCNTL_DENIED_COMMANDS_V1",
    "FUTEX_PRIVATE_FLAG_V1",
    "PIPE2_DENIED_FLAGS_V1",
    "FILESYSTEM_QUOTA_FD_WRITE_SYSCALLS_X86_64_V1",
    "FILESYSTEM_QUOTA_FD_TARGET_REGISTERS_X86_64_V1",
    "ExpectedFileIdentityV1",
    "ExpectedFileTypeV1",
    "FilesystemEvidenceV1",
    "FilesystemLimitKindV1",
    "FilesystemLimitObservationV1",
    "FilesystemLimitScopeV1",
    "FilesystemPolicyV1",
    "ISOLATION_EVIDENCE_SCHEMA_V1",
    "ISOLATION_PROFILE_V1",
    "ISOLATION_REQUEST_SCHEMA_V1",
    "IsolationRequestErrorCodeV1",
    "IsolationRequestV1",
    "IsolationRequestValidationV1",
    "LINUX_NATIVE_SUPERVISOR_V1",
    "LinuxNativeSupervisorV1",
    "MAX_EXEC_ARGUMENT_ENVIRONMENT_BYTES_V1",
    "MAX_LINUX_PATH_COMPONENTS_V1",
    "MAX_PRIVATE_FILESYSTEM_BYTES_V1",
    "MAX_PRIVATE_FILESYSTEM_INODES_V1",
    "MAX_RAW_STREAM_BYTES_V1",
    "MAX_RETAINED_STREAM_BYTES_V1",
    "MAX_RUNTIME_HORIZON_NS_V1",
    "NATIVE_SYSCALL_EXCLUSIVE_CEILING_X86_64_V1",
    "NetworkEvidenceV1",
    "NetworkModeV1",
    "NetworkPolicyV1",
    "OSObservationV1",
    "ObservationClassV1",
    "ObservedFileIdentityV1",
    "OutputPolicyV1",
    "ProcessEvidenceV1",
    "ProcessMemberEvidenceV1",
    "SecondaryExecDenialEvidenceV1",
    "PrivateMountQuotaEvidenceV1",
    "READ_ONLY_ALLOWED_INODE_TYPES_V1",
    "READ_ONLY_ROOT_SCAN_ENTRY_LIMIT_V1",
    "READ_ONLY_TOTAL_SCAN_ENTRY_LIMIT_V1",
    "ReadOnlyRootScanEvidenceV1",
    "ProcessPolicyV1",
    "REQUIRED_CAPABILITIES_V1",
    "REQUIRED_CAPABILITY_SET_SHA256_V1",
    "REQUIRED_FILESYSTEM_DENIAL_CLASSES_V1",
    "REQUIRED_MEMFD_SEALS_V1",
    "REQUIRED_NETWORK_DENIAL_CLASSES_V1",
    "REQUIRED_OBSERVATION_CLASSES_V1",
    "REQUIRED_OBSERVATION_EVENTS_V1",
    "REQUIRED_STAGE_DEPENDENCIES_V1",
    "ReadOnlyRootV1",
    "RequestIdentityV1",
    "SOCKET_DENIAL_FILTER_SHA256_V1",
    "SOCKET_DENIAL_FILTER_ROWS_V1",
    "SOCKET_DENIAL_UNCONDITIONAL_SYSCALLS_V1",
    "StageDependencyV1",
    "STREAM_PIPE_CAPACITY_BYTES_V1",
    "StreamCountV1",
    "StreamDecodingStatusV1",
    "StreamEvidenceV1",
    "StreamPolicyV1",
    "WorkloadIdentityV1",
    "X32_SYSCALL_BIT_V1",
    "execute_isolation_request_v1",
    "effective_exec_argv_v1",
    "effective_exec_environment_v1",
    "validate_execution_evidence_v1",
    "validate_isolation_request_v1",
]


def __getattr__(name: str) -> object:
    if name in {"LinuxNativeSupervisorV1", "execute_isolation_request_v1"}:
        from .linux_backend import (
            LinuxNativeSupervisorV1,
            execute_isolation_request_v1,
        )

        return {
            "LinuxNativeSupervisorV1": LinuxNativeSupervisorV1,
            "execute_isolation_request_v1": execute_isolation_request_v1,
        }[name]
    raise AttributeError(name)
